## 🟡 Pac-Man Contribution Game 👻

<p align="center">
  <img src="https://raw.githubusercontent.com/pranavgadekar96-sys/pranavgadekar96-sys/output/pacman.svg">
</p>

### 👻 Ghost Mode
<p align="center">
  <img src="https://raw.githubusercontent.com/pranavgadekar96-sys/pranavgadekar96-sys/output/pacman-ghost.svg">
</p>

### 🌈 Neon Mode
<p align="center">
  <img src="https://raw.githubusercontent.com/pranavgadekar96-sys/pranavgadekar96-sys/output/pacman-neon.svg">
</p>
